# Site settings
title: Codev Software, LLC
email: contact@codev.net
url: http://codev.net
description: "Codev Software, LLC, Boise, Full-stack web-app development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: 'orange'
  linkshover: '#ffcc66'

# Footer settings
footer: Codev Software, LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bitbucket
    url: https://bitbucket.org/codev-software-llc/
  - title: github
    url: https://github.com/codev-software-llc/

# Build settings
markdown: kramdown
permalink: pretty
